INSERT INTO public.noteful_notes
(title, "content", folder)
VALUES
('Noir', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut leo nunc, molestie quis euismod eleifend, tempus quis ligula. Pellentesque lacus enim, commodo non est ac, feugiat viverra magna. Aenean aliquet eget nulla quis congue. Duis et nibh nec massa laoreet ultrices. Aliquam posuere purus ac purus pretium sagittis. Ut egestas est sed dignissim venenatis. Donec pulvinar viverra lorem, sit amet laoreet ligula tincidunt non. Curabitur iaculis sapien ac libero rhoncus tempor. Mauris aliquet vitae eros rhoncus sagittis. In sagittis a ex sed mattis. Proin faucibus, dui ut luctus bibendum, ex magna condimentum mi, ac convallis nulla nisi in sem. Aenean volutpat mauris arcu, in tempus diam placerat in. Morbi a sollicitudin purus.', 1),
('Bleu', 'Ut eu commodo enim. Vestibulum mattis velit nunc, ut posuere neque molestie ut. Phasellus pellentesque at dui sit amet tincidunt. Suspendisse potenti. In vitae nulla consequat, aliquet arcu sed, sodales nulla. Phasellus vehicula est at mollis mollis. Cras non mi non libero finibus volutpat. Proin volutpat neque sit amet ante cursus ullamcorper. Fusce volutpat feugiat nunc in hendrerit.', 1),
('Vert', 'Ut sodales est elit, in molestie eros volutpat et. Morbi vel condimentum magna, et vulputate enim. Suspendisse non sapien vitae sem dignissim placerat et non quam. Proin congue nisi et laoreet maximus. Etiam id congue nulla, in hendrerit turpis. Suspendisse blandit nisl vitae turpis porta mattis. Suspendisse facilisis libero id ex efficitur euismod. Sed non mauris sapien. Sed erat dui, ultrices at sollicitudin scelerisque, consectetur quis turpis. Proin pulvinar diam eu massa eleifend vestibulum. Etiam iaculis nulla sagittis arcu rutrum faucibus.', 1),
('Marron', 'Fusce mollis nisl purus, eget suscipit sapien finibus at. Phasellus eu mauris turpis. Aenean luctus ligula nec nulla consequat, nec vestibulum augue mattis. Integer finibus ornare mi, ac fringilla tellus. Suspendisse potenti. Nullam nibh sapien, fermentum feugiat tincidunt quis, vulputate nec arcu. Proin pharetra erat at ipsum auctor, blandit tincidunt massa consectetur. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec scelerisque neque at libero convallis, commodo gravida enim pulvinar. Pellentesque facilisis auctor nisl non finibus. Phasellus ac lacinia tortor. Nunc placerat tellus nisl, eget molestie orci pharetra id. Proin maximus imperdiet lacus, et vestibulum leo vulputate eget.', 2),
('Orange', 'Curabitur auctor finibus erat, a vulputate nulla varius ac. Phasellus justo lectus, vehicula eget pulvinar eu, interdum a urna. Sed interdum, lectus sit amet viverra tincidunt, tellus felis tempor turpis, in venenatis dolor nisi quis nibh. Vivamus sed turpis non augue ultricies imperdiet et ultrices metus. Nam enim dolor, feugiat et consequat nec, pharetra ut nisi. Nunc fringilla ornare sem, quis volutpat neque efficitur quis. Suspendisse vestibulum arcu sit amet purus accumsan lobortis. Duis id finibus neque. Cras tristique ac libero id cursus. Nam id elementum sem. Morbi laoreet ligula non ligula pretium placerat. Vestibulum finibus urna sit amet neque pellentesque, id efficitur libero pretium. Ut ultrices efficitur enim vitae pretium.', 2),
('Rouge', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce augue lacus, auctor sit amet nulla eget, imperdiet ultrices risus. Quisque nec suscipit nisl. Aliquam ac ipsum in nunc vestibulum suscipit in quis risus. Fusce aliquam mauris ut consequat luctus. Etiam quis ex in dolor euismod bibendum. Suspendisse imperdiet odio sed scelerisque cursus. Vestibulum vitae risus tortor. Curabitur porta, odio in varius malesuada, tellus arcu iaculis erat, vitae tempor nulla felis ut risus. Fusce euismod elementum sem id semper. Vivamus tincidunt semper sapien. Donec eleifend ante ac sollicitudin tincidunt. In sit amet molestie elit. Suspendisse eget augue ut dolor vestibulum gravida. Pellentesque mollis risus metus, quis elementum libero finibus eget.', 3),
('Gris', 'Maecenas ut sodales nulla, quis eleifend ex. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam eu dui vel dolor maximus consequat. Morbi maximus magna ut nulla molestie, sit amet volutpat purus finibus. Vestibulum convallis id sem nec porttitor. Morbi libero orci, finibus quis tellus eleifend, feugiat tempor nibh. Integer volutpat, nibh eget lacinia sodales, massa nunc sagittis eros, at semper arcu elit eget tellus. Curabitur cursus, lacus vitae fringilla mollis, felis magna congue sem, sed hendrerit mi mi quis ex. Proin nec volutpat elit. Curabitur vehicula est dui, lacinia elementum lectus rutrum vel. Nulla dignissim commodo risus vitae pulvinar. Duis est ante, condimentum at elementum egestas, blandit eu lacus. Duis vitae ligula eget urna commodo vestibulum at ornare magna.', 3),
('Jaune', 'Vestibulum in nunc et justo maximus posuere vel ac enim. Fusce tristique rutrum pellentesque. Suspendisse potenti. Phasellus posuere leo vitae nibh pellentesque venenatis. Maecenas sed ullamcorper dolor. Nam eu porttitor turpis. Suspendisse at iaculis dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel ornare sapien, id varius dui.', 3),
('Blanc', 'Morbi quis orci varius, dignissim dolor at, rutrum justo. Cras dapibus nisi at venenatis convallis. Pellentesque et quam quis lorem ornare vulputate eu non ex. Etiam molestie nulla eget lectus lacinia, sit amet auctor ante tristique. Vivamus consequat mauris ex, quis dictum lectus sodales vitae. Proin eget blandit odio. Nulla velit urna, aliquet in tellus non, venenatis convallis risus. Suspendisse pharetra dictum magna, sit amet elementum arcu ultricies quis.', 4),
('Rose', 'Praesent id lectus augue. Quisque id sollicitudin felis, et pellentesque nunc. Integer a massa dignissim, semper velit ac, cursus sem. Phasellus aliquet accumsan eros sed pharetra. Aliquam vehicula est elit, eu consectetur metus bibendum non. Sed cursus dui a vestibulum sodales. Aliquam erat volutpat. Nam auctor elit vitae mi sollicitudin, non maximus erat porta.', 3),
('Violet', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sagittis, arcu ut sodales imperdiet, nisl nulla posuere felis, et commodo mauris tellus ut lorem. Etiam id tincidunt sapien. Pellentesque pulvinar neque vitae metus condimentum, non luctus magna posuere. Maecenas ornare eget felis vitae cursus. Morbi laoreet a mauris vel tempor. Curabitur turpis arcu, faucibus et viverra nec, tincidunt sed sapien. In in libero porta, molestie neque pulvinar, pharetra elit. Vivamus eleifend facilisis eros eget pharetra.', 1),
('Clair', 'Nam ut commodo magna. Praesent nulla purus, feugiat quis leo id, luctus ullamcorper sapien. Vivamus dictum erat at nulla feugiat gravida. Nulla rhoncus fringilla augue in varius. Donec ex orci, posuere ut ultrices eu, commodo eget justo. Duis quis lobortis metus. Sed viverra massa auctor est fermentum rhoncus. Suspendisse sit amet quam tempor lectus convallis euismod. Donec tempus leo nulla, sed bibendum nunc consectetur eu. Suspendisse sit amet lectus egestas, aliquam nisl id, finibus est. Integer et quam interdum, suscipit augue sed, pellentesque orci. Vivamus placerat et mi in commodo. Nulla luctus porta lorem nec fermentum. Donec vulputate, felis vitae egestas condimentum, velit eros fringilla libero, dignissim porta est justo id metus. Etiam vitae dolor in urna tincidunt feugiat.', 4);
